stages:
  prepare:
    cmd: python prepare.py
    deps:
      - prepare.py
      - data/dataset.csv
      - config.yaml
    outs:
      - data/processed

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/processed
      - config.yaml
    outs:
      - model.pkl
      - metrics.txt
